project_name: consul-config-manager

before:
  hooks:
    - go mod download

env:
  - CGO_ENABLED=0
  - GO111MODULE=on

builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/leads-su/version.version={{.Version}} -X github.com/leads-su/version.commit={{.Commit}} -X github.com/leads-su/version.buildDate={{.Date}} -X github.com/leads-su/version.builtBy=goreleaser

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - changelog*
      - CHANGELOG*
      - readme*
      - README*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^*.md:"
      - "^docs:"
      - "^test:"
